// src/routes/Important.jsx
import React from "react";
import { useQuery } from "@tanstack/react-query";
import { fetchTodos } from "../api/todo";
import { Link } from "@tanstack/react-router";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

export default function Important() {
  const {
    data: todos = [],
    isLoading,
    isError,
  } = useQuery({
    queryKey: ["todos"],
    queryFn: fetchTodos,
  });

  if (isLoading) {
    return (
      <Card className="">
        <CardContent className="p-6 space-y-2">
          <Skeleton className="h-8 w-1/4" />
          <Skeleton className="h-6 w-4/4" />
          <Skeleton className="h-6 w-4/4" />
          <Skeleton className="h-6 w-4/4" />
          <Skeleton className="h-6 w-4/4" />
        </CardContent>
      </Card>
    );
  }

  if (isError)
    return (
      <p className="animate-bounce max-w-md mx-auto bg-red-100 dark:bg-red-950 text-red-500">
        Failed to load important tasks.
      </p>
    );

  const highPriority = todos.filter((todo) => todo.priority === "HIGH");

  return (
    <div className="p-4">
      <h1 className="text-2xl font-bold mb-4">Important Tasks</h1>
      {highPriority.length === 0 ? (
        <p>No high-priority tasks.</p>
      ) : (
        <ul className="space-y-2 text-[19px]">
          {highPriority.map((todo) => (
            <li
              key={todo.id}
              className="p-2 border border-gray-500 rounded hover:bg-gray-100 dark:hover:bg-gray-600"
            >
              <Link to={`/app/todos/${todo.id}`} className="font-medium">
                {todo.name}
              </Link>
              <span
                className={`ml-2 text-sm sm:text-xs ${todo.status === "DONE" ? "text-green-500/85 max-sm:text-green-500 font-semibold" : todo.status === "IN_PROGRESS" ? "text-yellow-500/85 max-sm:text-yellow-500 font-semibold" : "text-orange-500/85 max-sm:text-orange-500 font-semibold"}`}
              >
                Status:{" "}
                {todo.status === "DONE"
                  ? " Completed"
                  : todo.status === "IN_PROGRESS"
                    ? " In Progress"
                    : " Todo"}
              </span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// src/views/Important.vue
<script setup lang="ts">
defineOptions({ name: 'ImportantTasks' })

import { computed } from 'vue'
import { useSeo } from '@/composables/useSeo'
import { useQuery } from '@tanstack/vue-query'
import { fetchTodos } from '@/api/todo'
import { RouterLink } from 'vue-router'
import { Card, CardContent } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import type { Todo } from '@/types/todo'

useSeo({ title: 'Important Tasks - T0+D0' })
const {
  data: todos,
  isLoading,
  isError,
} = useQuery({
  queryKey: ['todos'],
  queryFn: fetchTodos,
})

const highPriority = computed(() =>
  (todos.value || []).filter((todo: Todo) => todo.priority === 'HIGH' && !todo.archived),
)
</script>

<template>
  <div class="p-4">
    <h1 class="text-2xl font-bold mb-4">Important Tasks</h1>

    <Card v-if="isLoading">
      <CardContent class="p-6 space-y-2">
        <Skeleton class="h-8 w-full" />
        <Skeleton class="h-6 w-full" />
        <Skeleton class="h-6 w-full" />
        <Skeleton class="h-6 w-full" />
        <Skeleton class="h-6 w-full" />
      </CardContent>
    </Card>

    <p
      v-else-if="isError"
      class="animate-bounce max-w-md mx-auto bg-red-100 dark:bg-red-950 text-red-500"
    >
      Failed to load important tasks.
    </p>

    <div v-else>
      <p v-if="!isLoading && highPriority.length === 0">No high-priority tasks.</p>
      <ul v-else-if="!isLoading" class="space-y-2 text-[19px]">
        <li
          v-for="todo in highPriority"
          :key="todo.id"
          class="p-2 border border-gray-500 rounded hover:bg-gray-100 dark:hover:bg-gray-600"
        >
          <RouterLink :to="`/app/todos/${todo.id}`" class="font-medium">
            {{ todo.name }}
          </RouterLink>
          <span
            :class="[
              'ml-2 text-sm sm:text-xs font-semibold',
              todo.status === 'DONE'
                ? 'text-green-500/85 max-sm:text-green-500'
                : todo.status === 'IN_PROGRESS'
                  ? 'text-yellow-500/85 max-sm:text-yellow-500'
                  : 'text-orange-500/85 max-sm:text-orange-500',
            ]"
          >
            Status:
            {{
              todo.status === 'DONE'
                ? ' Completed'
                : todo.status === 'IN_PROGRESS'
                  ? ' In Progress'
                  : ' Todo'
            }}
          </span>
        </li>
      </ul>
    </div>
  </div>
</template>
