// todo-vue/src/components/UpdateTodoModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { useMutation, useQueryClient } from '@tanstack/vue-query'
import { updateTodo } from '@/api/todo'
import type { Todo, UpdateTodoData } from '@/types/todo'
import { toast } from 'vue-sonner'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

const props = defineProps<{
  isOpen: boolean,
  todo: Todo | null
}>()

const emit = defineEmits(['close'])

const queryClient = useQueryClient()

const formState = ref<UpdateTodoData>({})

const { isPending, mutate } = useMutation({
  mutationFn: (vars: { id: string, data: UpdateTodoData }) => updateTodo(vars.id, vars.data),
  onSuccess: () => {
    toast.success('Todo updated successfully!')
    
    // Invalidate both the todos list and the individual todo query
    queryClient.invalidateQueries({ queryKey: ['todos'] })
    if (props.todo?.id) {
      queryClient.invalidateQueries({ queryKey: ['todo', props.todo.id] })
    }
    emit('close')
  },
  onError: (error) => {
    console.error('Update failed:', error)
    toast.error('Failed to update todo. Please try again.')
  }
})

const handleSubmit = () => {
  if (props.todo && formState.value.name?.trim()) {
    console.log('Submitting form with data:', formState.value) // Debug log
    mutate({ id: props.todo.id, data: formState.value })
  }
}

watch(() => props.todo, (newTodo) => {
  if (newTodo) {
    formState.value = {
      name: newTodo.name || '',
      description: newTodo.description || '',
      status: newTodo.status || 'TODO',
      priority: newTodo.priority || 'LOW',
      archived: newTodo.archived || false,
    }
    console.log('Form state initialized:', formState.value) // Debug log
  }
}, { immediate: true })
</script>

<template>
  <Dialog :open="isOpen" @update:open="(val) => !val && emit('close')">
    <DialogContent v-if="todo">
      <DialogHeader>
        <DialogTitle>Update Todo</DialogTitle>
      </DialogHeader>
      <form @submit.prevent="handleSubmit">
        <div class="space-y-4 py-4">
            <div>
                <Label for="update-name">Name <span class="text-red-500">*</span></Label>
                <Input id="update-name" v-model="formState.name" :disabled="isPending" />
            </div>
            <div>
                <Label for="update-description">Description</Label>
                <Input id="update-description" v-model="formState.description" :disabled="isPending" />
            </div>
            <div>
                  <Label for="update-priority">Priority</Label>
                  <Select v-model="formState.priority" :disabled="isPending">
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="LOW">Low</SelectItem>
                      <SelectItem value="MEDIUM">Medium</SelectItem>
                      <SelectItem value="HIGH">High</SelectItem>
                    </SelectContent>
                  </Select>
            </div>
            <div>
                <Label for="update-status">Status</Label>
                <Select v-model="formState.status" :disabled="isPending">
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                    <SelectItem value="TODO">Todo</SelectItem>
                    <SelectItem value="IN_PROGRESS">In Progress</SelectItem>
                    <SelectItem value="DONE">Done</SelectItem>
                </SelectContent>
                </Select>
            </div>
            <div class="flex items-center space-x-2">
                <!-- Fixed Switch binding with debug -->
                <Switch 
                  id="update-archived" 
                  v-model:model-value="formState.archived"
                  :disabled="isPending" 
                />
                <Label for="update-archived">Archive</Label>
            </div>
        </div>
        <DialogFooter>
          <Button type="button" variant="outline" @click="emit('close')" :disabled="isPending">Cancel</Button>
          <Button type="submit" :disabled="!formState.name?.trim() || isPending">
            {{ isPending ? "Updating..." : "Update Todo" }}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>

// src/components/UpdateTodoModal.jsx
import React, { useEffect } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useForm } from "@tanstack/react-form";
import { updateTodo } from "../api/todo";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

export default function UpdateTodoModal({ isOpen, onClose, todo }) {
  const queryClient = useQueryClient();

  const updateTodoMutation = useMutation({
    mutationFn: ({ id, ...data }) => updateTodo(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["todos"] });
      onClose();
      form.reset();
    },
    onError: (error) => {
      console.error("Error updating todo:", error);
      // I may add toast notif here in the future
    },
  });

  const form = useForm({
    defaultValues: {
      name: todo?.name || "",
      description: todo?.description || "",
      status: todo?.status || "TODO",
      priority: todo?.status || "LOW",
    },
    onSubmit: async ({ value }) => {
      if (todo && value.name.trim()) {
        updateTodoMutation.mutate({ id: todo.id, ...value });
      }
    },
  });

  useEffect(() => {
    if (isOpen && todo) {
      form.reset({
        name: todo.name || "",
        description: todo.description || "",
        status: todo.status || "TODO",
      });
    }
  }, [isOpen, todo, form]);

  useEffect(() => {
    if (!isOpen) {
      form.reset();
    }
  }, [isOpen, form]);

  if (!todo) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Update Todo</DialogTitle>
        </DialogHeader>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            e.stopPropagation();
            form.handleSubmit();
          }}
        >
          <div className="space-y-4 py-4">
            <form.Field
              name="name"
              validators={{
                onChange: ({ value }) =>
                  !value || !value.trim() ? "Name is required" : undefined,
              }}
            >
              {(field) => (
                <div>
                  <Label htmlFor="update-name">
                    Name <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="update-name"
                    value={field.state.value}
                    onChange={(e) => field.handleChange(e.target.value)}
                    onBlur={field.handleBlur}
                    placeholder="Enter todo name..."
                    disabled={updateTodoMutation.isPending}
                  />
                  {field.state.meta.errors.length > 0 && (
                    <p className="text-sm text-red-500 mt-1">
                      {field.state.meta.errors[0]}
                    </p>
                  )}
                </div>
              )}
            </form.Field>

            <form.Field name="description">
              {(field) => (
                <div>
                  <Label htmlFor="update-description">Description</Label>
                  <Input
                    id="update-description"
                    value={field.state.value}
                    onChange={(e) => field.handleChange(e.target.value)}
                    onBlur={field.handleBlur}
                    placeholder="Enter description ..."
                    disabled={updateTodoMutation.isPending}
                  />
                </div>
              )}
            </form.Field>

            <form.Field name="priority">
              {(field) => (
                <div>
                  <Label htmlFor="update-priority">Priority</Label>
                  <Select
                    id="update-priority"
                    value={field.state.value}
                    onValueChange={field.handleChange}
                    disabled={updateTodoMutation.isPending}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="LOW">Low</SelectItem>
                      <SelectItem value="MEDIUM">Medium</SelectItem>
                      <SelectItem value="HIGH">High</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              )}
            </form.Field>

            <form.Field name="status">
              {(field) => (
                <div>
                  <Label htmlFor="update-status">Status</Label>
                  <Select
                    value={field.state.value}
                    onValueChange={(value) => field.handleChange(value)}
                    disabled={updateTodoMutation.isPending}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="TODO">Todo</SelectItem>
                      <SelectItem value="IN_PROGRESS">In Progress</SelectItem>
                      <SelectItem value="DONE">Done</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              )}
            </form.Field>

            <form.Field name="archived">
              {(field) => (
                <div className="flex items-center space-x-2">
                  <Switch
                    id="update-archived"
                    checked={field.state.value}
                    onCheckedChange={field.handleChange}
                    disabled={updateTodoMutation.isPending}
                  />
                  <Label htmlFor="update-archived">Archive</Label>
                </div>
              )}
            </form.Field>
          </div>
          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={onClose}
              className="max-sm:mt-2 max-sm:font-semibold"
              disabled={updateTodoMutation.isPending}
            >
              Cancel
            </Button>
            <form.Subscribe
              selector={(state) => [state.canSubmit, state.isSubmitting]}
            >
              {([canSubmit]) => (
                <Button
                  type="submit"
                  className="max-sm:font-semibold"
                  disabled={!canSubmit || updateTodoMutation.isPending}
                >
                  {updateTodoMutation.isPending ? "Updating..." : "Update Todo"}
                </Button>
              )}
            </form.Subscribe>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
